version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@shikijs/*"
        update-types:
          - "minor"
          - "patch"
      all-security:
        applies-to: security-updates
        patterns:
          - "*"
